### ISSUE TITLE
catch exception when get data

### ISSUE THREAD

**Issue by hellobiek** [hellobiek/smart_deal_tool#1]
Traceback (most recent call last):
  File "/Users/hellobiek/anaconda/lib/python2.7/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "httpd.py", line 29, in get_stock_realtime_info
    s.set_realtime_stock_info()
  File "/Users/hellobiek/Documents/workspace/quant/smart_deal_tool/common.py", line 36, in _wrapper
    return func(*args, **kargs)
  File "/Users/hellobiek/Documents/workspace/quant/smart_deal_tool/stock.py", line 555, in set_realtime_stock_info
    _info = ts.get_realtime_quotes(stock_codes)
  File "/Users/hellobiek/anaconda/lib/python2.7/site-packages/tushare/stock/trading.py", line 369, in get_realtime_quotes
    text = urlopen(request,timeout=10).read()
  File "/Users/hellobiek/anaconda/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/hellobiek/anaconda/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/Users/hellobiek/anaconda/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/Users/hellobiek/anaconda/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/Users/hellobiek/anaconda/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/Users/hellobiek/anaconda/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 60] Operation timed out>
Fri Dec  1 14:40:18 2017 <Greenlet at 0x10e2e1b90: get_stock_realtime_info(10)> failed with URLError

**Comment by hellobiek** [comment]
catch exception
